export const SIGNUP_ERROR_CODE = {
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  NOT_ALLOW_EMPTY_EMAIL: 'NOT_ALLOW_EMPTY_EMAIL',
  ALREADY_EXIST_MEMBER_WITH_DUPLICATED_EMAIL: 'ALREADY_EXIST_MEMBER_WITH_DUPLICATED_EMAIL',
  NOT_ALLOW_EMPTY_NAME: 'NOT_ALLOW_EMPTY_NAME',
  INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
} as const;

export const LOGIN_ERROR_CODE = {
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  NOT_FOUND_MEMBER_WITH_EMAIL: 'NOT_FOUND_MEMBER_WITH_EMAIL',
  INVALID_PASSWORD_FORMAT: 'INVALID_PASSWORD_FORMAT',
} as const;
